sttitle: Ecoflore
theme: jekyll-theme-tactile
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
sass:
  style: compressed
  load_paths:
    - _sass
    - assets/css

# Ajouter le lien vers le CSS personnalis√©
extra:
  head: |
    <link rel="stylesheet" href="{{ '/assets/css/custom.css' | relative_url }}">
lang: fr

